### PR TITLE
pipeline: add pipewire dependency and pipewiresrc support to gaeguli …

### PR DESCRIPTION
**Pull request by raghaven447**
…library

Added libpipewire-0.3 as a build dependency. pipewiresrc is added to the
GaeguliVideoSource enum so that pipewiresrc may be used as default video source.

### CODE REVIEW

**Comment by raghaven447** [comment]
This PR aims at adding libpipewire-0.3 as a build dependency. pipewiresrc can be used as default video source replacing v4l2src. I would like to add Multi process with pipewire in another PR.

**Comment by justinjoy** [comment]
> This PR aims at adding libpipewire-0.3 as a build dependency. pipewiresrc can be used as default video source replacing v4l2src. I would like to add Multi process with pipewire in another PR.

I think we need to create an experimental branch that doesn't depend on ubuntu matters.
Can you provide a whole series of commits to solving the library dependency problem by meson's subproject?
If you define `.wrap` in the subprojects folder, it might be an easy solution to gather and build libraries before starting gaeguli build, although it will take longer than using pre-built libraries that are provided by ubuntu 20.04.

**Comment by raghaven447** [comment]
Sure. I shall define .wrap in sub-projects folder and update the patch

**Comment by raghaven447** [comment]
Since most of the projects on which Pipewire depends (for example, libsndfile, alsalib, blueZ, SBC, Jack etc) do not have meson build support, I believe that we may need to use them as dependencies. Please comment.

**Comment by justinjoy** [comment]
> Since most of the projects on which Pipewire depends (for example, libsndfile, alsalib, blueZ, SBC, Jack etc) do not have meson build support, I believe that we may need to use them as dependencies. Please comment.

As you have sent MR that includes only `pipewire-0.3`, I thought we can use the other dependencies that ubuntu 20.04 provides. According to `meson.build` of pipewire 0.3.17 branch, it requires only `libsndfile(=> 1.0.20)`,  `alsa(>=1.1.7)` and `gstreamer-1.0(>=1.10)`. That means we can use the other dependencies that ubuntu 20.04 provides as `-dev` packages.

I think it is enough to install dev packages in github action workflow to enable CI/CD properly. 
Or do you need another reason to update the other dependencies for using pipewire-0.3?

**Comment by raghaven447** [comment]
I believe installing dev packages is enough. Along with libsndfile, alsa and gstreamer installing dev packages of sbc, bluez and jack is required to build pipewire.

**Comment by raghaven447** [comment]
Closing this PR as per the revised changes.

**Pull request closed without merging**
